name: Benchmark (Main)

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/CODEOWNERS'
      - '.github/dependabot.yml'

permissions:
  contents: read

jobs:
  benchmark:
    uses: ./.github/workflows/benchmark-publish.yml
    permissions:
      contents: write
    with:
      ref: ${{ github.sha }}
      commit-message: 'chore: update benchmark results [skip ci]'
